### ISSUE TITLE
Roadmap to v2.0.0

### ISSUE THREAD

**Issue by ganderzz** [ganderzz/react-scroll-to#56]
To make react-scroll-to even easier to use, there are some breaking changes that need to happen. We should look to v2.0.0 to provide these changes.

- [x] Convert children function to take an object instead of arguments. This will allow for destructuring `<ScrollTo>{({ scrollById }) => ()</ScrollTo>` (#57)
- [x] Add ability to `scrollByRef(ref)` (#62)
- [x] Update to use React 16.3's new context
- [x] Update unit tests to match v2.0.0 new features/improvements
- [x] Implement smooth scrolling  (#48) 
- [x] Update Typescript definitions to match v2.0.0 new features/improvements
- [x] Add more docs (#63)
- [x] Update, design, and implement github pages for React Storybook (#64)

All changes should be merged into: https://github.com/ganderzz/react-scroll-to/tree/release/2.0.0
